### ISSUE TITLE
Не хочет опубликовываться в Яндекс.Диалоге

### ISSUE THREAD

**Issue by kostasoft** [jeyroik/php-yandex-alisa-simple#1]
Привет! Спасибо за реализацию на php!
Но не публикуется.
Ругается так: Ошибка в ответе Webhook

Хотя через Postman на запрос с сервера (Подсмотрел в логе):
`{"meta":{"client_id":"Developer Console","locale":"ru-RU","timezone":"UTC"},"request":{"command":"test","original_utterance":"test","type":"SimpleUtterance"},"session":{"message_id":0,"new":true,"session_id":"61c5f901-22ba20bd-534104b2-1db70","skill_id":"3bbaf06a-1318-4f90-a9da-0a37c7967d8f","user_id":"FB80F23261CBB89F7D78B179AB439E543267D498BCADAAB0CE6223108268C08D"},"version":"1.0"}`
отвечает так:
```
{
    "version": "1.0",
    "session": {
        "session_id": "61c5f901-22ba20bd-534104b2-1db70",
        "message_id": 0,
        "user_id": "FB80F23261CBB89F7D78B179AB439E543267D498BCADAAB0CE6223108268C08D"
    },
    "response": {
        "text": "В вашем запросе 4 символов",
        "tts": "в в+ашем запр+осе 4 с+имволов",
        "buttons": [],
        "end_session": false
    }
}
```
Вроде все совпадает с [инструкцией](https://tech.yandex.ru/dialogs/alice/doc/protocol-docpage/)...
Что может быть?

**Comment by Areso** [comment]
@kostasoft смотрите мой вариант, теперь проходит валидацию.
